variable "count" {}
variable "type" {}
variable "blockSize" {}
variable "ami" {}
variable "keyname" {}
variable "cycle" {}
variable "server_tag_Name" {}
variable "server_tag_Role" {}
variable "securitygroupid" {}
variable "subnet_id" {}
